packages:
  - apps/*
  - packages/*
  - playgrounds/

allowBuilds:
  '@prisma/engines': false
  cn-font-split: true
  core-js: false
  esbuild: true
  koffi: true
  msw: false
  prisma: false
  protobufjs: false
  sharp: true

catalog:
  '@tailwindcss/postcss': ^4.3.0
  '@tailwindcss/vite': ^4.3.0
  '@types/node': ^25.7.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@vitejs/plugin-react': ^6.0.1
  echarts: ^6.0.0
  es-toolkit: ^1.46.1
  eslint: ^9.39.4
  framer-motion: ^12.38.0
  lucide-react: ^1.14.0
  next: ^16.2.6
  react: ^19.2.6
  react-dom: ^19.2.6
  tailwindcss: ^4.3.0
  tsx: ^4.21.0
  vite: ^8.0.12

patchedDependencies:
  '@monaco-editor/loader': patches/@monaco-editor__loader.patch
