export type { MDXClientProps } from './components/client'
export type { MDXCodeProps } from './components/code'
export type { MDXHeadingProps } from './components/heading'
export type { MDXServerProps } from './components/server'

export { MDXClient } from './components/client'
export { MDXCode } from './components/code'
export { components } from './components/elements'
export { MDXHeading } from './components/heading'
export { MDXServer } from './components/server'
